apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  labels:
    app: notification-service
    component: backend
    service: notification-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::145023091806:role/cloudmart-notification-service-role
  namespace: cloudmart-prod
automountServiceAccountToken: true