apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: cloudmart-prod
  labels:
    app: product-service
    component: backend
    service: product-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::145023091806:role/cloudmart-product-service-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: cloudmart-staging
  labels:
    app: product-service
    component: backend
    service: product-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::145023091806:role/cloudmart-product-service-role
automountServiceAccountToken: true