apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: cloudmart-prod
  labels:
    app: user-service
    component: backend
    service: user-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::145023091806:role/cloudmart-user-service-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: cloudmart-staging
  labels:
    app: user-service
    component: backend
    service: user-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::145023091806:role/cloudmart-user-service-role
automountServiceAccountToken: true