apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend.yaml
  - notification-service.yaml
  - product-service.yaml
  - order-service.yaml
  - user-service.yaml
