apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: 145023091806.dkr.ecr.ap-south-1.amazonaws.com/cloudmart/order-service
    newTag: 302b65941b02409c59243036f6901f20f93a1b8a