apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: 145023091806.dkr.ecr.ap-south-1.amazonaws.com/cloudmart/order-service
    newTag: e416102af083581851500f635af763eb7b5d11b6