apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: 145023091806.dkr.ecr.ap-south-1.amazonaws.com/cloudmart/user-service
    newTag: 1e5c3edd8ade52f08062ff96a592ae56cc68ffe5