apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize to compile all the sub-folders together
resources:
  - frontend
  - notification-service
  - order-service
  - product-service
  - user-service